// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4uoB54JSwIUH9iv6LL-upJZJJgxUmro',
    appId: '1:319297262752:web:c9f9ede49e47a810ca65c5',
    messagingSenderId: '319297262752',
    projectId: 'palorahai-auth',
    authDomain: 'palorahai-auth.firebaseapp.com',
    storageBucket: 'palorahai-auth.appspot.com',
    measurementId: 'G-ELEP7LRDG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwE2fagvcP54brdyH5gnOWBzMK3FimfI',
    appId: '1:319297262752:android:f4d1508b80b1568fca65c5',
    messagingSenderId: '319297262752',
    projectId: 'palorahai-auth',
    storageBucket: 'palorahai-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5cXNRO-jG_wxRPkHbflFaEBxnILxDq0',
    appId: '1:319297262752:ios:4506986ab63a5470ca65c5',
    messagingSenderId: '319297262752',
    projectId: 'palorahai-auth',
    storageBucket: 'palorahai-auth.appspot.com',
    iosBundleId: 'com.PalorahAI.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5cXNRO-jG_wxRPkHbflFaEBxnILxDq0',
    appId: '1:319297262752:ios:713a1552912307a5ca65c5',
    messagingSenderId: '319297262752',
    projectId: 'palorahai-auth',
    storageBucket: 'palorahai-auth.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe4uoB54JSwIUH9iv6LL-upJZJJgxUmro',
    appId: '1:319297262752:web:1b5f68f4d73ce64dca65c5',
    messagingSenderId: '319297262752',
    projectId: 'palorahai-auth',
    authDomain: 'palorahai-auth.firebaseapp.com',
    storageBucket: 'palorahai-auth.appspot.com',
    measurementId: 'G-TYP1YSYYZD',
  );
}
